### ISSUE TITLE
Two column view - sinkage issue

### ISSUE THREAD

**Issue by ghost** [fiduswriter/paginate-for-print#1]
When the text is viewed in two or more columns, the half of the page is left blank.
can it fill the entire page fill with the contents? 
![untitled](https://cloud.githubusercontent.com/assets/11002621/16227409/04015fc6-37ce-11e6-9e15-13da39cc943f.png)

**Comment by johanneswilm** [comment]
Hey, yes, actually I didn't start work on two column layout, although this is a much requested feature. @williamjl What did you do to specify that you wanted two column layout?

**Comment by ghost** [comment]
When the page has mixed style of content (single and double column), the entire page should have contents. The white space should not exi
![untitled1](https://cloud.githubusercontent.com/assets/11002621/16227980/bf3fb582-37d1-11e6-9557-0829a0e42200.png)
st

**Comment by johanneswilm** [comment]
Absolutely. But how did you specify it? Did you simply use CSS properties?

**Comment by ghost** [comment]
yes, column style is with css

**Comment by johanneswilm** [comment]
Fixed in release 0.0.3

**Comment by ghost** [comment]
Thanks Sir, it is working great!
